### ISSUE TITLE
ID

### ISSUE THREAD

**Issue by Belllam** [pgh268400/NWebtoon_Downloader#4]
i need i help in the id of the progrem 
how i can put my id in it

**Comment by pgh268400** [comment]
READ THIS https://pgh268400.tistory.com/216
(Maybe you need a translator if you're a foreigner.)

If you want to download adult comics, you do not need to provide your ID to the program. Instead, you must provide cookie values called NID_AUT and NID_SES, which are present in the Google Chrome browser.

![image](https://github.com/pgh268400/NWebtoon_Downloader/assets/31213158/84e1e99f-7ed9-4ae2-9ac6-3f37d878b187)
After logging in to Naver, you can press F12 and obtain the cookie value.

**Comment by Belllam** [comment]
i bought a chapter and it’s open now to read, but when i try to download it, it doesn’t work 
can you help me what i should do to download it?

**Comment by pgh268400** [comment]
No. This program does not work with purchased chapters. Downloading purchashed chapter requires disabling DRM protection, which is illegal.

**Comment by pgh268400** [comment]
As you can see from the commit history, I’ve noticed the recent issue and I’m working on patches. However, since this service is not something I get paid to maintain and I already have many other tasks, I plan to release a fix when I have the time. (There’s no scheduled date for the release.) Regarding the original Tistory post, I wasn’t aware either, but it seems it was removed due to a deletion request from Naver. I believe that explanation is at least partially true. Recently, Naver has been reacting sensitively to programs related to their services, and as a result, this project may also encounter related issues. Please also note that I may discontinue this project at any time at my own discretion.
